use std::fs;

use codegraph::{CodeGraph, IndexOptions};

const GENERATED_PAYROLL: &str = r#"package payroll

// Code generated by fkit. DO NOT EDIT.

type PayrollRecord struct { Amount int }
func BuildPayslip() error { return nil }
"#;

const HANDWRITTEN_WORKFLOW: &str = r#"package payroll

// BuildPayslip implements the monthly payroll rule.
func BuildPayslip() error { return nil }
"#;

#[tokio::test(flavor = "current_thread")]
async fn generated_metadata_persists_and_unions_with_path_fallback() {
    let dir = tempfile::tempdir().expect("tempdir");
    fs::write(dir.path().join("payroll.go"), GENERATED_PAYROLL).expect("write generated");
    fs::write(dir.path().join("workflow.go"), HANDWRITTEN_WORKFLOW).expect("write handwritten");
    fs::write(
        dir.path().join("payroll.pb.go"),
        "package payroll\ntype PayrollProto struct{}\n",
    )
    .expect("write path generated");

    let cg = CodeGraph::init_sync(dir.path()).expect("init");
    let indexed = cg.index_all(&IndexOptions::default()).await.expect("index");
    assert!(indexed.success, "index errors: {:?}", indexed.errors);

    let mut candidates = vec![
        "payroll.go".to_string(),
        "workflow.go".to_string(),
        "payroll.pb.go".to_string(),
    ];
    candidates.extend((0..600).map(|index| format!("missing/{index}.go")));
    let generated = cg.generated_file_predicate(&candidates).expect("predicate");
    assert!(generated.is_generated("payroll.go"));
    assert!(generated.is_generated("payroll.pb.go"));
    assert!(!generated.is_generated("workflow.go"));
    assert_eq!(cg.get_generated_file_count().expect("count"), 2);

    let fallback = cg
        .generated_file_predicate(&[])
        .expect("fallback predicate");
    assert!(fallback.is_generated("some/other/tx.pb.go"));
    assert!(!fallback.is_generated("some/other/keeper.go"));

    let persisted: i64 =
        rusqlite::Connection::open(dir.path().join(".codegraph").join("codegraph.db"))
            .expect("open database")
            .query_row(
                "SELECT generated FROM files WHERE path = 'payroll.go'",
                [],
                |row| row.get(0),
            )
            .expect("persisted flag");
    assert_eq!(persisted, 1);

    let connection = rusqlite::Connection::open(dir.path().join(".codegraph").join("codegraph.db"))
        .expect("open database for legacy simulation");
    connection
        .execute("UPDATE files SET generated = 0", [])
        .expect("simulate un-backfilled v9 rows");
    let unbackfilled = cg
        .generated_file_predicate(&candidates)
        .expect("unbackfilled predicate");
    assert!(unbackfilled.is_generated("payroll.pb.go"));
    assert!(!unbackfilled.is_generated("payroll.go"));
}

#[tokio::test(flavor = "current_thread")]
async fn sync_clears_and_restores_the_header_verdict() {
    let dir = tempfile::tempdir().expect("tempdir");
    fs::write(dir.path().join("payroll.go"), GENERATED_PAYROLL).expect("write generated");
    let cg = CodeGraph::init_sync(dir.path()).expect("init");
    cg.index_all(&IndexOptions::default()).await.expect("index");

    fs::write(dir.path().join("payroll.go"), HANDWRITTEN_WORKFLOW).expect("remove banner");
    cg.sync(&IndexOptions::default()).await.expect("sync clear");
    assert_eq!(cg.get_generated_file_count().expect("cleared count"), 0);

    fs::write(dir.path().join("payroll.go"), GENERATED_PAYROLL).expect("restore banner");
    cg.sync(&IndexOptions::default())
        .await
        .expect("sync restore");
    assert_eq!(cg.get_generated_file_count().expect("restored count"), 1);
}
