use std::collections::HashSet;
use std::sync::LazyLock;

pub(in crate::resolution::resolver) static JVM_STDLIB_EXTERNAL_CALLS: LazyLock<
    HashSet<&'static str>,
> = LazyLock::new(|| {
    HashSet::from([
        "AssertionError",
        "assert",
        "assertFalse",
        "assertEquals",
        "assertNotNull",
        "assertNull",
        "assertSame",
        "assertThrows",
        "assertTrue",
        "assertThat",
        "containsString",
        "empty",
        "equalTo",
        "expectThrows",
        "greaterThan",
        "hasItem",
        "hasSize",
        "instanceOf",
        "is",
        "lessThan",
        "mock",
        "not",
        "notNullValue",
        "nullValue",
        "sameInstance",
        "when",
        "any",
        "check",
        "checkNotNull",
        "emptyList",
        "emptyMap",
        "emptySet",
        "error",
        "hashCode",
        "let",
        "listOf",
        "mapOf",
        "require",
        "requireNotNull",
        "run",
        "setOf",
        "toString",
        "List.of",
        "Map.of",
        "Set.of",
        "Objects.equals",
    ])
});

pub(in crate::resolution::resolver) static JVM_STDLIB_TYPES: LazyLock<HashSet<&'static str>> =
    LazyLock::new(|| {
        HashSet::from([
            "ArrayList",
            "Boolean",
            "Byte",
            "CharSequence",
            "Class",
            "Double",
            "Enum",
            "Exception",
            "Float",
            "HashMap",
            "HashSet",
            "IllegalArgumentException",
            "IllegalStateException",
            "Integer",
            "IOException",
            "Iterable",
            "LinkedHashMap",
            "LinkedHashSet",
            "List",
            "Long",
            "Map",
            "Object",
            "Optional",
            "RuntimeException",
            "Set",
            "Short",
            "String",
            "Throwable",
            "TreeMap",
            "TreeSet",
        ])
    });

pub(in crate::resolution::resolver) const JVM_STDLIB_IMPORT_PREFIXES: [&str; 7] = [
    "java.",
    "javax.",
    "jakarta.",
    "kotlin.",
    "org.hamcrest.",
    "org.junit.",
    "org.mockito.",
];

pub(in crate::resolution::resolver) static JVM_NAMESPACE_SEGMENTS: LazyLock<HashSet<&'static str>> =
    LazyLock::new(|| {
        HashSet::from([
            "android",
            "backend",
            "com",
            "common",
            "generated",
            "gradle",
            "idea",
            "io",
            "java",
            "javax",
            "jetbrains",
            "jvm",
            "kotlin",
            "lang",
            "metadata",
            "net",
            "org",
            "proto",
            "protobuf",
            "serialization",
            "util",
        ])
    });
