//! Generated-file detection for symbol-disambiguation down-ranking.
//!
//! When a query like "Send" matches 17 symbols across protobuf scaffolding,
//! test mocks, and the hand-written implementation, the FTS ranker often
//! surfaces the generated stubs first because their names are identical
//! to the implementation's name (validated empirically on cosmos-sdk —
//! see project_go_multi_module_audit memory). Generated stubs frequently
//! have no body to trace from, so the agent ends up reading source anyway.
//!
//! Path conventions remain the no-database fallback. During indexing, a
//! bounded header scan is unioned with that path signal and persisted for
//! candidate-list ranking. Generated nodes remain reachable; they rank after
//! a hand-written implementation with the same name.

use std::collections::HashSet;
use std::sync::LazyLock;

use regex::{Regex, RegexSet};

static GENERATED_PATTERNS: LazyLock<RegexSet> = LazyLock::new(|| {
    RegexSet::new([
        // Go — protobuf / gRPC / pulsar
        r"\.pb\.go$",
        r"\.pulsar\.go$",
        r"_grpc\.pb\.go$",
        // Go — mockgen output. Default emits `mock_<src>.go`; many projects
        // (cosmos-sdk uses `expected_*_mocks.go`) rename to `*_mock.go` /
        // `*_mocks.go`. Matching either suffix catches both conventions
        // without false-positive risk on hand-written sources.
        r"_mock\.go$",
        r"_mocks\.go$",
        r"^mock_[^/]+\.go$",
        // TypeScript / JavaScript — common codegen suffixes (Apollo / GraphQL
        // codegen, Prisma, Hasura, ts-proto, gRPC-web, swagger-codegen).
        r"\.generated\.[jt]sx?$",
        r"\.gen\.[jt]sx?$",
        r"\.pb\.[jt]s$",
        r"_pb\.[jt]s$",
        r"_grpc_pb\.[jt]s$",
        r"\.min\.m?js$",
        // Python — protobuf / gRPC / openapi-codegen
        r"_pb2(_grpc)?\.py$",
        r"_pb2\.pyi$",
        // C++ — protobuf
        r"\.pb\.(cc|h)$",
        // C# — protobuf / gRPC (protoc-gen-csharp puts output under obj/ but
        // many projects also commit *.g.cs and *Grpc.cs siblings)
        r"\.g\.cs$",
        r"Grpc\.cs$",
        // Java — protobuf / gRPC: protoc-gen-java emits `*OuterClass.java`,
        // protoc-gen-grpc-java emits `*Grpc.java`. The XxxImplBase abstract
        // class lives inside Xxx*Grpc.java.
        r"OuterClass\.java$",
        r"Grpc\.java$",
        // Swift — protobuf
        r"\.pb\.swift$",
        // Dart — build_runner / freezed / json_serializable / chopper
        r"\.g\.dart$",
        r"\.freezed\.dart$",
        r"\.pb\.dart$",
        r"\.pbgrpc\.dart$",
        r"\.chopper\.dart$",
        // Rust — common build.rs OUT_DIR outputs are usually outside the source
        // tree, but in-tree generated files often use `*.generated.rs`.
        r"\.generated\.rs$",
    ])
    .expect("valid generated-file patterns")
});

/// Whether `file_path` looks like a tool-generated source file based on
/// its filename. Path-only — does not read content. The result is a
/// relevance hint for disambiguation, not a hard claim.
pub fn is_generated_file(file_path: &str) -> bool {
    GENERATED_PATTERNS.is_match(file_path)
}

const HEADER_SCAN_BYTES: usize = 8192;
const HEADER_SCAN_LINES: usize = 60;

static GENERATED_STEM: LazyLock<Regex> =
    LazyLock::new(|| Regex::new("(?i)generat").expect("valid generated stem"));

static COMMENT_LEADER: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r#"(?i)^\s*(?://|/\*+|\*+/??|#+|--+|<!--|%+|;+|'|!|\(\*|\{-|\"\"\"|'''|=begin|<#|@rem\b|rem\b)"#,
    )
    .expect("valid comment leader")
});

static GENERATED_CONTENT_PATTERNS: LazyLock<RegexSet> = LazyLock::new(|| {
    RegexSet::new([
        r"(?i)\bcode generated\b.{0,200}?\bdo not edit\b",
        r"(?i)\b(?:automatically |auto[- ]?)?generated (?:by|from|with)\b.{0,200}?\bdo not (?:edit|modify|change)\b",
        r"(?:^|[^\p{L}\p{N}_@])@generated\b",
        r"(?i)<auto-?generated\s*/?>",
        r"(?i)\b(?:automatically generated|auto[- ]?generated|autogenerated) by\b",
        r"(?i)\bgenerated by\s+\S.{0,80}?\bby running\b",
        r"(?i)\bthis (?:file|class|code|module) (?:is|was) (?:auto[- ]?)?generated\b",
        r"(?i)\bdo not (?:edit|modify)\b.{0,120}?\b(?:auto[- ]?generated|generated file|generated code)\b",
    ])
    .expect("valid generated-content patterns")
});

const BLOCK_DELIMITERS: [(&str, &str); 6] = [
    ("/*", "*/"),
    ("<!--", "-->"),
    ("\"\"\"", "\"\"\""),
    ("'''", "'''"),
    ("=begin", "=end"),
    ("<#", "#>"),
];

/// Whether a bounded source header carries a recognized generator banner.
pub fn has_generated_header(content: &str) -> bool {
    if content.is_empty() {
        return false;
    }
    let head = if content.len() <= HEADER_SCAN_BYTES {
        content
    } else {
        let end = content
            .char_indices()
            .map(|(index, _)| index)
            .take_while(|index| *index <= HEADER_SCAN_BYTES)
            .last()
            .unwrap_or(0);
        &content[..end]
    };
    if !GENERATED_STEM.is_match(head) {
        return false;
    }

    let mut open_block: Option<(&str, &str)> = None;
    for line in head.lines().take(HEADER_SCAN_LINES) {
        if (open_block.is_some() || COMMENT_LEADER.is_match(line))
            && GENERATED_CONTENT_PATTERNS.is_match(line)
        {
            return true;
        }

        if let Some((_, close)) = open_block {
            if line.contains(close) {
                open_block = None;
            }
            continue;
        }
        for (open, close) in BLOCK_DELIMITERS {
            let Some(at) = line.find(open) else {
                continue;
            };
            if !line[at + open.len()..].contains(close) {
                open_block = Some((open, close));
            }
            break;
        }
    }
    false
}

/// The path-or-header verdict persisted when source is indexed.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GenerationStatus {
    Generated,
    HandWritten,
}

impl GenerationStatus {
    pub fn detect(file_path: &str, content: &str) -> Self {
        if detect_generated_file(file_path, content) {
            Self::Generated
        } else {
            Self::HandWritten
        }
    }

    pub const fn as_i64(self) -> i64 {
        match self {
            Self::Generated => 1,
            Self::HandWritten => 0,
        }
    }
}

/// Whether either the path convention or source header marks a file generated.
pub fn detect_generated_file(file_path: &str, content: &str) -> bool {
    is_generated_file(file_path) || has_generated_header(content)
}

/// Bounded generated-file lookup used by ranking comparators.
pub struct GeneratedFilePredicate {
    indexed_paths: HashSet<String>,
}

impl GeneratedFilePredicate {
    pub(crate) fn new(indexed_paths: HashSet<String>) -> Self {
        Self { indexed_paths }
    }

    pub fn is_generated(&self, file_path: &str) -> bool {
        self.indexed_paths.contains(file_path) || is_generated_file(file_path)
    }
}

#[cfg(test)]
mod tests;
