//! Generated-file detection for symbol-disambiguation down-ranking.
//!
//! When a query like "Send" matches 17 symbols across protobuf scaffolding,
//! test mocks, and the hand-written implementation, the FTS ranker often
//! surfaces the generated stubs first because their names are identical
//! to the implementation's name (validated empirically on cosmos-sdk —
//! see project_go_multi_module_audit memory). Generated stubs frequently
//! have no body to trace from, so the agent ends up reading source anyway.
//!
//! This helper is a pure path-based classifier consulted at disambiguation
//! time (findSymbol / findAllSymbols / codegraph_search formatting), NOT
//! a hard filter — generated nodes are still in the graph and remain
//! reachable; they just rank LAST when there's a real implementation
//! with the same name.
//!
//! Scope: suffix patterns only. Most generated files follow the
//! `<basename>.<tool>.<ext>` convention (`.pb.go`, `_grpc.pb.go`,
//! `.g.dart`, `_pb2.py`), and that covers ~all of what we saw in the
//! Go audit. A future addition would be scanning for the canonical
//! `// Code generated by` header during extraction, for the rare files
//! that defy the suffix convention.

use std::sync::LazyLock;

use regex::RegexSet;

static GENERATED_PATTERNS: LazyLock<RegexSet> = LazyLock::new(|| {
    RegexSet::new([
        // Go — protobuf / gRPC / pulsar
        r"\.pb\.go$",
        r"\.pulsar\.go$",
        r"_grpc\.pb\.go$",
        // Go — mockgen output. Default emits `mock_<src>.go`; many projects
        // (cosmos-sdk uses `expected_*_mocks.go`) rename to `*_mock.go` /
        // `*_mocks.go`. Matching either suffix catches both conventions
        // without false-positive risk on hand-written sources.
        r"_mock\.go$",
        r"_mocks\.go$",
        r"^mock_[^/]+\.go$",
        // TypeScript / JavaScript — common codegen suffixes (Apollo / GraphQL
        // codegen, Prisma, Hasura, ts-proto, gRPC-web, swagger-codegen).
        r"\.generated\.[jt]sx?$",
        r"\.gen\.[jt]sx?$",
        r"\.pb\.[jt]s$",
        r"_pb\.[jt]s$",
        r"_grpc_pb\.[jt]s$",
        // Python — protobuf / gRPC / openapi-codegen
        r"_pb2(_grpc)?\.py$",
        r"_pb2\.pyi$",
        // C++ — protobuf
        r"\.pb\.(cc|h)$",
        // C# — protobuf / gRPC (protoc-gen-csharp puts output under obj/ but
        // many projects also commit *.g.cs and *Grpc.cs siblings)
        r"\.g\.cs$",
        r"Grpc\.cs$",
        // Java — protobuf / gRPC: protoc-gen-java emits `*OuterClass.java`,
        // protoc-gen-grpc-java emits `*Grpc.java`. The XxxImplBase abstract
        // class lives inside Xxx*Grpc.java.
        r"OuterClass\.java$",
        r"Grpc\.java$",
        // Swift — protobuf
        r"\.pb\.swift$",
        // Dart — build_runner / freezed / json_serializable / chopper
        r"\.g\.dart$",
        r"\.freezed\.dart$",
        r"\.pb\.dart$",
        r"\.pbgrpc\.dart$",
        r"\.chopper\.dart$",
        // Rust — common build.rs OUT_DIR outputs are usually outside the source
        // tree, but in-tree generated files often use `*.generated.rs`.
        r"\.generated\.rs$",
    ])
    .expect("valid generated-file patterns")
});

/// Whether `file_path` looks like a tool-generated source file based on
/// its filename. Path-only — does not read content. The result is a
/// relevance hint for disambiguation, not a hard claim.
pub fn is_generated_file(file_path: &str) -> bool {
    GENERATED_PATTERNS.is_match(file_path)
}

#[cfg(test)]
mod tests {
    //! Regression coverage for the generated-file detector that drives
    //! symbol-disambiguation down-ranking. Locked here because the suffix
    //! list is a contract: if a future edit drops `.pb.go`, the cosmos-sdk
    //! trace endpoint regresses to the gRPC stub.
    //! Ported from `__tests__/generated-detection.test.ts`.

    use super::is_generated_file;

    #[test]
    fn classifies_go_protobuf_grpc_pulsar_mock_outputs_as_generated() {
        assert!(is_generated_file("api/cosmos/bank/v1beta1/tx_grpc.pb.go"));
        assert!(is_generated_file("x/bank/types/tx.pb.go"));
        assert!(is_generated_file("api/cosmos/bank/v1beta1/tx.pulsar.go"));
        // cosmos-sdk uses `<base>_mocks.go`; mockgen's default is `mock_<src>.go`;
        // many projects use `<base>_mock.go`. All three are mockgen output.
        assert!(is_generated_file(
            "x/auth/testutil/expected_keepers_mocks.go"
        ));
        assert!(is_generated_file("internal/foo_mock.go"));
        assert!(is_generated_file("mock_keeper.go"));
    }

    #[test]
    fn does_not_flag_the_hand_written_keeper_as_generated() {
        assert!(!is_generated_file("x/bank/keeper/msg_server.go"));
        assert!(!is_generated_file("x/bank/keeper/send.go"));
    }

    #[test]
    fn catches_common_cross_language_codegen_suffixes() {
        assert!(is_generated_file("app/foo.generated.ts"));
        assert!(is_generated_file("app/foo.generated.tsx"));
        assert!(is_generated_file("proto/bar_pb2.py"));
        assert!(is_generated_file("proto/bar_pb2_grpc.py"));
        assert!(is_generated_file("lib/baz.pb.cc"));
        assert!(is_generated_file("lib/baz.pb.h"));
        assert!(is_generated_file("lib/quux.g.dart"));
        assert!(is_generated_file("lib/quux.freezed.dart"));
    }

    #[test]
    fn leaves_ordinary_source_files_alone() {
        assert!(!is_generated_file("src/index.ts"));
        assert!(!is_generated_file("src/components/Foo.tsx"));
        assert!(!is_generated_file("lib/main.dart"));
        assert!(!is_generated_file("cmd/server/main.go"));
        assert!(!is_generated_file("app/db.py"));
    }
}
