//! A test harness for a function no test reaches: one `#[test]` per
//! deterministic input, in a small crate that depends on the project's
//! crate by path (`.codegraph/miri/harness/<package>/tests/<target>.rs`).
//!
//! The function is called the way `fuzz-harness` calls it — the same
//! [`RustCallable`] (public path, receiver constructor, parameter forms) and
//! the same call rendering ([`push_call`]) — but on fixed inputs instead of
//! a fuzzer's: for a byte buffer the empty slice, one byte (`0x00`,
//! `0xff`), 32 bytes starting one past an 8-aligned address (so a cast to a
//! wider integer pointer is misaligned) and a 64-byte pattern; for text
//! the same idea in UTF-8 (empty, one char, multi-byte, NUL, unaligned);
//! for scalars and small collections a few edge values. Each input is its
//! own test, so Miri's report names the input that failed.
//!
//! Unsafe functions are not harnessed: their contract is the caller's, and
//! UB from inputs that break it would prove nothing about the function.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::analyze::fuzz::model::InputShape;
use crate::analyze::fuzz::rust::RustCallable;
use crate::analyze::fuzz::rust::harness::{push_call, target_name};
use crate::analyze::fuzz::rust::types::{ArgForm, split_top_level};

/// A generated Miri harness, before it is written.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HarnessText {
    /// The test binary (`tests/<target>.rs`).
    pub target: String,
    pub source: String,
    /// The `#[test]` functions, one per input.
    pub cases: Vec<String>,
}

/// Byte inputs: name and the statements binding `data: &[u8]`.
const BYTE_CASES: &[(&str, &str)] = &[
    ("empty", "let data: &[u8] = &[];"),
    ("one_zero_byte", "let data: &[u8] = &[0x00];"),
    ("one_high_byte", "let data: &[u8] = &[0xff];"),
    (
        "unaligned_32",
        "let storage = Aligned(core::array::from_fn(|i| (i * 37 % 251) as u8));\n    let data: &[u8] = &storage.0[1..33];",
    ),
    (
        "pattern_64",
        "let bytes: Vec<u8> = (0..64u32).map(|i| (i * 73 % 256) as u8).collect();\n    let data: &[u8] = &bytes;",
    ),
];

/// Text inputs: name and the statements binding `text: &str` (and `data`,
/// its bytes, for a reader or a byte parameter beside it).
const TEXT_CASES: &[(&str, &str)] = &[
    ("empty", "let text: &str = \"\";"),
    ("one_char", "let text: &str = \"a\";"),
    ("multibyte", "let text: &str = \"é€𝄞\";"),
    ("nul", "let text: &str = \"\\0\";"),
    (
        "unaligned_32",
        "let storage = Aligned(core::array::from_fn(|i| b'a' + (i % 26) as u8));\n    let text: &str = std::str::from_utf8(&storage.0[1..33]).unwrap();",
    ),
    (
        "long_ascii",
        "let owned: String = \"codegraph-miri \".repeat(5);\n    let text: &str = &owned;",
    ),
];

/// The harness for `callable`, or why it cannot be generated.
pub fn render(callable: &RustCallable) -> Result<HarnessText, String> {
    if callable.is_unsafe {
        return Err(
            "an unsafe fn: its safety contract is the caller's, so inputs a harness \
                    makes up could break it without proving anything"
                .into(),
        );
    }
    if callable.is_async {
        return Err("an async fn: a harness would need an executor".into());
    }
    if !callable.todos.is_empty() {
        return Err(format!(
            "the harness cannot build every input: {}",
            callable.todos.join("; ")
        ));
    }
    let params = callable.all_params();
    let data_params = params.iter().filter(|p| p.form.shape().is_data()).count();
    let value_params = params
        .iter()
        .filter(|p| p.form.shape() == InputShape::Structured)
        .count();
    let target = format!("miri_{}", target_name(callable));
    let mut source = String::new();
    let _ = writeln!(
        source,
        "//! Miri harness for `{}` ({}:{}): one test per input.\n//!\n//! Generated by \
         `codegraph analyze miri`; run with `cargo +nightly miri test --test {target}`.\n\
         #![allow(unused_variables, unused_mut, clippy::all)]\n",
        callable.display_path(),
        callable.span.file,
        callable.span.start_line
    );
    if let Some(import) = &callable.trait_import {
        let _ = writeln!(source, "#[allow(unused_imports)]\nuse {import};\n");
    }
    source.push_str(
        "/// Storage aligned to 8, so a slice from index 1 is misaligned for\n\
         /// every integer wider than a byte.\n\
         #[repr(C, align(8))]\n\
         struct Aligned([u8; 40]);\n",
    );

    let mut cases: Vec<(String, String)> = Vec::new();
    if value_params == 0 && data_params <= 1 {
        let text = params.iter().any(|p| p.form.shape() == InputShape::Text);
        let bytes = params.iter().any(|p| p.form.shape().is_data());
        let inputs: Vec<(&str, String)> = if text {
            TEXT_CASES
                .iter()
                .map(|(name, bind)| {
                    (
                        *name,
                        format!("    {bind}\n    let data: &[u8] = text.as_bytes();\n"),
                    )
                })
                .collect()
        } else if bytes {
            BYTE_CASES
                .iter()
                .map(|(name, bind)| (*name, format!("    {bind}\n")))
                .collect()
        } else {
            vec![("call", String::new())]
        };
        for (name, bind) in inputs {
            let mut body = bind;
            let mut args = Vec::new();
            for param in &params {
                match param.form.from_buffer() {
                    Some(arg) => args.push(arg),
                    None => return Err(format!("cannot pass `{}: {}`", param.name, param.ty)),
                }
            }
            push_call(callable, args, &mut body);
            cases.push((name.to_string(), body));
        }
    } else {
        // One local per parameter, each from its own list of edge values;
        // case i takes value i (wrapping) of every list.
        let mut lists: Vec<(String, String, Vec<String>)> = Vec::new();
        for (position, param) in params.iter().enumerate() {
            let Some(field) = param.form.field_type() else {
                continue;
            };
            let values = literals(&field)
                .ok_or_else(|| format!("no fixed values for `{}: {}`", param.name, param.ty))?;
            lists.push((format!("arg{position}"), field, values));
        }
        let count = lists.iter().map(|(_, _, v)| v.len()).max().unwrap_or(1);
        for case in 0..count {
            let mut body = String::new();
            for (local, field, values) in &lists {
                let _ = writeln!(
                    body,
                    "    let mut {local}: {field} = {};",
                    values[case % values.len()]
                );
            }
            let mut args = Vec::new();
            for (position, param) in params.iter().enumerate() {
                args.push(match param.form {
                    ArgForm::Opaque => {
                        return Err(format!("cannot build `{}: {}`", param.name, param.ty));
                    }
                    _ => param.form.from_field(&format!("arg{position}")),
                });
            }
            push_call(callable, args, &mut body);
            cases.push((format!("values_{case}"), body));
        }
    }
    for (name, body) in &cases {
        let _ = write!(source, "\n#[test]\nfn {name}() {{\n{body}}}\n");
    }
    Ok(HarnessText {
        target,
        source,
        cases: cases.into_iter().map(|(name, _)| name).collect(),
    })
}

/// A few edge values of a field type the fuzz harness would fill with
/// `Arbitrary` (`u32`, `Vec<u16>`, `Option<bool>`, `(u8, String)`), as
/// Rust expressions; `None` for a type with no fixed values here.
pub fn literals(ty: &str) -> Option<Vec<String>> {
    let ty = ty.trim();
    let list = |items: &[&str]| Some(items.iter().map(|s| s.to_string()).collect());
    match ty {
        "u8" | "u16" | "u32" | "u64" | "u128" | "usize" => {
            return list(&["0", "1", "7", "255"]);
        }
        "i8" => return list(&["0", "1", "-1", "127"]),
        "i16" | "i32" | "i64" | "i128" | "isize" => return list(&["0", "1", "-1", "300"]),
        "bool" => return list(&["false", "true"]),
        "char" => return list(&["'a'", "'é'", "'\\0'"]),
        "f32" | "f64" => return list(&["0.0", "1.5", "-1.0", &format!("{ty}::NAN")]),
        "String" => {
            return list(&["String::new()", "\"a\".to_string()", "\"é€𝄞\".to_string()"]);
        }
        "()" => return list(&["()"]),
        _ => {}
    }
    if let Some(inner) = generic_arg(ty, "Vec") {
        if inner == "u8" {
            return list(&["Vec::new()", "vec![0x00]", "vec![0xff; 17]"]);
        }
        let values = literals(inner)?;
        let many: Vec<&str> = values.iter().map(String::as_str).take(3).collect();
        return Some(vec![
            "Vec::new()".to_string(),
            format!("vec![{}]", values[0]),
            format!("vec![{}]", many.join(", ")),
        ]);
    }
    if let Some(inner) = generic_arg(ty, "Option") {
        let values = literals(inner)?;
        let mut out = vec!["None".to_string()];
        out.extend(values.iter().take(2).map(|v| format!("Some({v})")));
        return Some(out);
    }
    if let Some(inner) = ty.strip_prefix('[').and_then(|t| t.strip_suffix(']')) {
        let (element, len) = inner.rsplit_once(';')?;
        let len = len.trim();
        let values = literals(element)?;
        return Some(
            values
                .iter()
                .take(2)
                .map(|v| format!("[{v}; {len}]"))
                .collect(),
        );
    }
    if let Some(inner) = ty.strip_prefix('(').and_then(|t| t.strip_suffix(')')) {
        let parts: Vec<Vec<String>> = split_top_level(inner, ',')
            .into_iter()
            .map(str::trim)
            .filter(|p| !p.is_empty())
            .map(literals)
            .collect::<Option<_>>()?;
        let count = parts.iter().map(Vec::len).max()?;
        return Some(
            (0..count)
                .map(|i| {
                    let items: Vec<&str> = parts.iter().map(|p| p[i % p.len()].as_str()).collect();
                    format!("({},)", items.join(", "))
                })
                .collect(),
        );
    }
    None
}

/// `T` of `Name<T>`.
fn generic_arg<'a>(ty: &'a str, name: &str) -> Option<&'a str> {
    ty.strip_prefix(name)?
        .trim()
        .strip_prefix('<')?
        .strip_suffix('>')
        .map(str::trim)
}

/// Where harnesses of `package` go.
pub fn harness_dir(root: &Path, package: &str) -> PathBuf {
    root.join(".codegraph")
        .join("miri")
        .join("harness")
        .join(package)
}

/// The harness crate's manifest: the project's crate by path, a workspace
/// of its own (so a parent workspace does not claim it).
pub fn cargo_toml(package: &str, crate_path: &Path) -> String {
    format!(
        "[package]\nname = \"{package}-codegraph-miri\"\nversion = \"0.0.0\"\nedition = \"2021\"\n\
         publish = false\n\n[dependencies.{package}]\npath = \"{}\"\n\n[workspace]\nmembers = [\".\"]\n",
        crate_path.display().to_string().replace('\\', "/")
    )
}

/// Write `harness` for `callable` into `dir` (its `Cargo.toml` when
/// missing, the project's `Cargo.lock` when it has none — offline builds
/// then pick the versions the project already uses).
pub fn write(
    root: &Path,
    callable: &RustCallable,
    harness: &HarnessText,
    dir: &Path,
) -> Result<(), String> {
    let tests = dir.join("tests");
    std::fs::create_dir_all(&tests)
        .map_err(|e| format!("cannot create {}: {e}", tests.display()))?;
    let crate_dir = root.join(&callable.krate.dir);
    let crate_dir = crate_dir.canonicalize().unwrap_or(crate_dir);
    let manifest = dir.join("Cargo.toml");
    let wanted = cargo_toml(&callable.krate.package, &crate_dir);
    if std::fs::read_to_string(&manifest).ok().as_deref() != Some(wanted.as_str()) {
        std::fs::write(&manifest, wanted)
            .map_err(|e| format!("cannot write {}: {e}", manifest.display()))?;
    }
    let lock = dir.join("Cargo.lock");
    if !lock.exists() {
        let mut at = Some(crate_dir.as_path());
        while let Some(current) = at {
            let candidate = current.join("Cargo.lock");
            if candidate.is_file() {
                let _ = std::fs::copy(&candidate, &lock);
                break;
            }
            if current == root {
                break;
            }
            at = current.parent();
        }
    }
    let file = tests.join(format!("{}.rs", harness.target));
    std::fs::write(&file, &harness.source)
        .map_err(|e| format!("cannot write {}: {e}", file.display()))?;
    let gitignore = dir.join(".gitignore");
    if !gitignore.exists() {
        let _ = std::fs::write(&gitignore, "target\nlogs\n");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn edge_values_cover_scalars_and_small_collections() {
        assert_eq!(literals("u32").unwrap(), ["0", "1", "7", "255"]);
        assert_eq!(literals("i8").unwrap()[3], "127");
        assert_eq!(
            literals("Vec<u8>").unwrap(),
            ["Vec::new()", "vec![0x00]", "vec![0xff; 17]"]
        );
        assert_eq!(
            literals("Vec<u16>").unwrap(),
            ["Vec::new()", "vec![0]", "vec![0, 1, 7]"]
        );
        assert_eq!(
            literals("Option<bool>").unwrap(),
            ["None", "Some(false)", "Some(true)"]
        );
        assert_eq!(literals("[u8; 4]").unwrap(), ["[0; 4]", "[1; 4]"]);
        assert_eq!(literals("(u8, bool)").unwrap()[1], "(1, true,)");
        assert!(literals("MyType").is_none());
        assert!(literals("Vec<MyType>").is_none());
    }
}
