fn assert_path_before(text: &str, first: &str, second: &str) {
    let first_at = text.find(first).unwrap_or_else(|| panic!("missing {first}: {text}"));
    let second_at = text.find(second).unwrap_or_else(|| panic!("missing {second}: {text}"));
    assert!(first_at < second_at, "expected {first} before {second}: {text}");
}

#[tokio::test(flavor = "current_thread")]
async fn search_node_and_explore_rank_header_generated_collisions_last_without_hiding_them() {
    let dir = TempDir::new().unwrap();
    write(
        &dir.path().join("payroll.go"),
        "package payroll\n\n// Code generated by fkit. DO NOT EDIT.\nfunc BuildPayslip() error { return nil }\n",
    );
    write(
        &dir.path().join("workflow.go"),
        "package payroll\n\n// BuildPayslip implements the monthly rule.\nfunc BuildPayslip() error { return nil }\n",
    );
    let cg = CodeGraph::init_sync(dir.path()).unwrap();
    cg.index_all(&IndexOptions::default()).await.unwrap();
    let handler = ToolHandler::new(Some(Rc::new(cg)));

    for (tool, arguments) in [
        ("codegraph_search", json!({ "query": "BuildPayslip" })),
        ("codegraph_node", json!({ "symbol": "BuildPayslip" })),
        ("codegraph_explore", json!({ "query": "BuildPayslip" })),
    ] {
        let result = handler.execute(tool, &arguments);
        assert_ne!(result.is_error, Some(true), "{tool}: {}", result.text());
        assert_path_before(result.text(), "workflow.go", "payroll.go");
    }
}
