use std::fs;

use super::{detect_generated_file, has_generated_header, is_generated_file};

#[test]
fn classifies_go_protobuf_grpc_pulsar_mock_outputs_as_generated() {
    assert!(is_generated_file("api/cosmos/bank/v1beta1/tx_grpc.pb.go"));
    assert!(is_generated_file("x/bank/types/tx.pb.go"));
    assert!(is_generated_file("api/cosmos/bank/v1beta1/tx.pulsar.go"));
    assert!(is_generated_file(
        "x/auth/testutil/expected_keepers_mocks.go"
    ));
    assert!(is_generated_file("internal/foo_mock.go"));
    assert!(is_generated_file("mock_keeper.go"));
}

#[test]
fn does_not_flag_the_hand_written_keeper_as_generated() {
    assert!(!is_generated_file("x/bank/keeper/msg_server.go"));
    assert!(!is_generated_file("x/bank/keeper/send.go"));
}

#[test]
fn catches_common_cross_language_codegen_suffixes() {
    for path in [
        "app/foo.generated.ts",
        "app/foo.generated.tsx",
        "public/app.min.mjs",
        "proto/bar_pb2.py",
        "proto/bar_pb2_grpc.py",
        "lib/baz.pb.cc",
        "lib/baz.pb.h",
        "lib/quux.g.dart",
        "lib/quux.freezed.dart",
    ] {
        assert!(is_generated_file(path), "{path}");
    }
}

#[test]
fn leaves_ordinary_source_files_alone() {
    for path in [
        "src/index.ts",
        "src/components/Foo.tsx",
        "lib/main.dart",
        "cmd/server/main.go",
        "app/db.py",
    ] {
        assert!(!is_generated_file(path), "{path}");
    }
}

#[test]
fn recognizes_every_source_header_fixture() {
    let generated = [
        "package payroll\n\n// Code generated by fkit. DO NOT EDIT.\n",
        "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n",
        "//go:build !windows\n// +build !windows\n\n// Code generated by MockGen. DO NOT EDIT.\npackage mocks\n",
        "// Copyright 2021 The Foo Authors.\n// Licensed under the Apache License, Version 2.0\n// Unless required by applicable law\n\n// Code generated by sqlc. DO NOT EDIT.\npackage db\n",
        "// Generated by the protocol buffer compiler.  DO NOT EDIT!\npackage com.example;\n",
        "# -*- coding: utf-8 -*-\n# Generated by the protocol buffer compiler.  DO NOT EDIT!\n",
        "// <auto-generated>\n// This code was generated by a tool.\n// </auto-generated>\n",
        "// <auto-generated />\nusing System;\n",
        "/**\n * @generated SignedSource<<0123456789abcdef>>\n */\n",
        "// @generated by protoc-gen-es v1.2.0\n",
        "/**\n * Autogenerated by Thrift Compiler (0.14.1)\n */\n",
        "/*\n * NOTE: This class is auto generated by OpenAPI Generator.\n */\n",
        "// automatically generated by the FlatBuffers compiler, do not modify\n",
        "/* automatically generated by rust-bindgen 0.59.2 */\n",
        "// Generated from Expr.g4 by ANTLR 4.9.2 -- DO NOT EDIT\n",
        "// Generated by Wrangler by running `wrangler types` (hash: abc)\n",
        "# Generated by ./scripts/schema-gen.py by running `make schema`\n",
        "/*\n   Code generated by ent. DO NOT EDIT.\n*/\n",
        "\"\"\"Generated by the protocol buffer compiler.  DO NOT EDIT!\"\"\"\n",
        "# This file is generated by kustomize. Do not edit.\n",
        "-- Code generated by sqlc. DO NOT EDIT.\n",
        "<!-- Autogenerated by docgen. Do not edit. -->\n",
    ];
    for source in generated {
        assert!(has_generated_header(source), "{source}");
    }
}

#[test]
fn rejects_every_source_control_fixture() {
    let handwritten = [
        "package keeper\n\n// SendCoins moves coins between accounts.\n",
        "// This package generates SQL migrations from the schema.\n// The generated output lives under db/migrations.\n",
        "\"\"\"The summary table is automatically generated at runtime from rows.\"\"\"\n",
        "package main\n\nfunc header() string { return \"// Code generated by fkit. DO NOT EDIT.\" }\n",
        "// Contact: build@generated.example.com for issues.\n",
        "// DO NOT EDIT THIS FILE BY HAND — run `make fmt` instead.\n",
        "// The table below is generated by the build at runtime.\n",
        "// The nightly summary is generated by running the ETL job.\n",
        "",
    ];
    for source in handwritten {
        assert!(!has_generated_header(source), "{source}");
    }
}

#[test]
fn header_scan_is_bounded_by_lines() {
    let long = (0..80)
        .map(|i| format!("// filler line {i}"))
        .collect::<Vec<_>>()
        .join("\n");
    assert!(!has_generated_header(&format!(
        "{long}\n// Code generated by foo. DO NOT EDIT.\n"
    )));
    let short = (0..20)
        .map(|i| format!("// filler line {i}"))
        .collect::<Vec<_>>()
        .join("\n");
    assert!(has_generated_header(&format!(
        "{short}\n// Code generated by foo. DO NOT EDIT.\n"
    )));
}

#[test]
fn requires_a_comment_line() {
    assert!(!has_generated_header(
        "const banner = \"Code generated by tool. DO NOT EDIT.\";\n"
    ));
}

#[test]
fn detector_does_not_classify_itself() {
    let source = fs::read_to_string(file!().replace("/tests.rs", ".rs")).expect("read detector");
    assert!(!has_generated_header(&source));
}

#[test]
fn union_detects_path_or_header_without_false_positives() {
    assert!(detect_generated_file(
        "x/bank/types/tx.pb.go",
        "package types\n"
    ));
    assert!(detect_generated_file(
        "internal/payroll/payroll.go",
        "package payroll\n\n// Code generated by fkit. DO NOT EDIT.\n"
    ));
    assert!(!is_generated_file("internal/payroll/payroll.go"));
    assert!(!detect_generated_file(
        "internal/payroll/workflow.go",
        "package payroll\n\n// RunPayrollWorkflow drives the monthly run.\n"
    ));
}
