//! A cargo-fuzz project around one [`RustCallable`]: `fuzz/Cargo.toml`
//! depending on the crate by path, and `fuzz/fuzz_targets/<name>.rs` with a
//! `libfuzzer-sys` `fuzz_target!`.
//!
//! Two shapes, chosen by what the target takes (constructor included):
//!
//! - **one buffer** — at most one bytes/text/reader parameter and nothing
//!   else: the fuzzer's `data: &[u8]` goes straight in (`&str` through
//!   `std::str::from_utf8`, skipping invalid UTF-8; a reader as a
//!   `Cursor`);
//! - **input struct** — several parameters, or scalars: a generated
//!   `#[derive(arbitrary::Arbitrary)] struct Input` with one field per
//!   parameter.
//!
//! Values the harness cannot build become `todo!("…")` bindings with a
//! `TODO` comment, so the file still says exactly what is missing. The text
//! is a pure function of the callable: generation is deterministic.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use serde::Serialize;

use super::types::ArgForm;
use super::{CallForm, Drain, HarnessParam, RustCallable, Wrap};
use crate::analyze::fuzz::model::InputShape;

/// The generated harness, before it is written.
#[derive(Debug, Clone)]
pub struct HarnessText {
    /// The cargo-fuzz target (`[[bin]] name`, file stem).
    pub target: String,
    pub source: String,
    pub needs_arbitrary: bool,
}

/// A file the harness wrote, and what happened to it.
#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct WrittenFile {
    pub path: String,
    /// `created`, `updated` or `unchanged`.
    pub status: &'static str,
}

/// The fuzz target name for a callable: its crate-relative public path in
/// snake case (`bcder::string::BitString::from_content` →
/// `string_bit_string_from_content`).
pub fn target_name(callable: &RustCallable) -> String {
    let path = callable.display_path();
    let segments: Vec<String> = path
        .split("::")
        .skip(1)
        .map(snake_case)
        .filter(|s| !s.is_empty())
        .collect();
    if segments.is_empty() {
        snake_case(&callable.span.name)
    } else {
        segments.join("_")
    }
}

fn snake_case(name: &str) -> String {
    let mut out = String::new();
    let mut previous_lower = false;
    for ch in name.chars() {
        if ch.is_uppercase() {
            if previous_lower {
                out.push('_');
            }
            out.extend(ch.to_lowercase());
            previous_lower = false;
        } else if ch.is_alphanumeric() || ch == '_' {
            out.push(ch);
            previous_lower = ch.is_lowercase() || ch.is_ascii_digit();
        }
    }
    out.trim_matches('_').to_string()
}

/// Render the harness source for `callable`.
pub fn render(callable: &RustCallable) -> HarnessText {
    let target = target_name(callable);
    let params = callable.all_params();
    let data_params = params.iter().filter(|p| p.form.shape().is_data()).count();
    let value_params = params
        .iter()
        .filter(|p| p.form.shape() == InputShape::Structured)
        .count();
    let structured = value_params > 0 || data_params > 1;

    let mut out = String::new();
    out.push_str("#![no_main]\n");
    if !callable.todos.is_empty() {
        out.push_str("#![allow(unreachable_code, unused_variables)]\n");
    }
    let _ = writeln!(
        out,
        "//! Fuzz `{}` ({}:{}).\n//!\n//! Generated by `codegraph analyze fuzz-harness`; run it with\n//! `cargo +nightly fuzz run {target}`.",
        callable.display_path(),
        callable.span.file,
        callable.span.start_line
    );
    for todo in &callable.todos {
        let _ = writeln!(out, "// TODO: {todo}");
    }
    out.push('\n');
    out.push_str("use libfuzzer_sys::fuzz_target;\n");
    if let Some(import) = &callable.trait_import {
        if !is_prelude_trait(import) {
            let _ = writeln!(out, "#[allow(unused_imports)]\nuse {import};");
        }
    }
    out.push('\n');

    // Field (or local) names, unique in declaration order.
    let mut names: Vec<String> = Vec::new();
    for param in &params {
        let mut name = param.name.clone();
        let mut suffix = 2;
        while names.contains(&name) || name == "data" || name == "text" || name == "input" {
            name = format!("{}_{suffix}", param.name);
            suffix += 1;
        }
        names.push(name);
    }

    let mut body = String::new();
    let mut args: Vec<String> = Vec::new();
    let mut capped: Vec<String> = Vec::new();
    if structured {
        out.push_str("#[derive(arbitrary::Arbitrary, Debug)]\nstruct Input {\n");
        for (param, name) in params.iter().zip(&names) {
            if let Some(field) = param.form.field_type() {
                let _ = writeln!(out, "    {name}: {field},");
            }
        }
        out.push_str("}\n\n");
        out.push_str("fuzz_target!(|input: Input| {\n");
        if params.iter().any(|p| p.form.needs_mut()) {
            body.push_str("    let mut input = input;\n");
        }
        for (param, name) in params.iter().zip(&names) {
            if param.form == ArgForm::Opaque {
                let _ = writeln!(
                    body,
                    "    let {name} = todo!(\"build `{}: {}`\");",
                    param.name,
                    escape(&param.ty)
                );
                args.push(name.clone());
            } else {
                let arg = param.form.from_field(&format!("input.{name}"));
                args.push(if is_size_like(param) {
                    capped.push(param.name.clone());
                    format!("{arg} % {SIZE_CAP}")
                } else {
                    arg
                });
            }
        }
    } else {
        let text = params.iter().any(|p| p.form.shape() == InputShape::Text);
        let uses_data = data_params > 0;
        let _ = writeln!(
            out,
            "fuzz_target!(|{}: &[u8]| {{",
            if uses_data { "data" } else { "_data" }
        );
        if text {
            body.push_str(
                "    let Ok(text) = std::str::from_utf8(data) else {\n        return;\n    };\n",
            );
        }
        for (param, name) in params.iter().zip(&names) {
            match param.form.from_buffer() {
                Some(arg) => args.push(arg),
                None => {
                    let _ = writeln!(
                        body,
                        "    let {name} = todo!(\"build `{}: {}`\");",
                        param.name,
                        escape(&param.ty)
                    );
                    args.push(name.clone());
                }
            }
        }
    }

    push_call(callable, args, &mut body);
    if !capped.is_empty() {
        let _ = writeln!(
            out,
            "    // Size-like arguments ({}) are taken modulo {SIZE_CAP} so allocations stay bounded.",
            capped.join(", ")
        );
    }
    out.push_str(&body);
    out.push_str("});\n");

    HarnessText {
        target,
        source: out,
        needs_arbitrary: structured,
    }
}

/// Append the statements that call `callable` with `args` (the
/// constructor's arguments first, then the target's) to `body`: the
/// receiver from its constructor (`return` when that fails), then the call,
/// its result drained when it is a lazy iterator. The Miri harness
/// (`analyze::miri::harness`) calls the same way.
pub(crate) fn push_call(callable: &RustCallable, args: Vec<String>, body: &mut String) {
    // Arguments split between constructor and target, in order.
    let (constructor_args, target_args) = match &callable.call {
        CallForm::Method {
            constructor: Some(constructor),
            ..
        } => {
            let n = constructor.params.len();
            (args[..n].to_vec(), args[n..].to_vec())
        }
        _ => (Vec::new(), args),
    };
    let turbofish = callable.turbofish.as_deref().unwrap_or("");
    let call = match &callable.call {
        CallForm::Path(path) => format!("{path}{turbofish}({})", target_args.join(", ")),
        CallForm::Method {
            name,
            owner_path,
            constructor,
        } => {
            match constructor {
                Some(constructor) => {
                    let built = format!("{}({})", constructor.call, constructor_args.join(", "));
                    let _ = match constructor.wrap {
                        Wrap::Plain => writeln!(body, "    let mut value = {built};"),
                        Wrap::Result => writeln!(
                            body,
                            "    let Ok(mut value) = {built} else {{\n        return;\n    }};"
                        ),
                        Wrap::Option => writeln!(
                            body,
                            "    let Some(mut value) = {built} else {{\n        return;\n    }};"
                        ),
                    };
                }
                None => {
                    let _ = writeln!(
                        body,
                        "    let mut value: {owner_path} = todo!(\"construct the receiver\");"
                    );
                }
            }
            format!("value.{name}{turbofish}({})", target_args.join(", "))
        }
    };
    let call = if callable.is_unsafe {
        format!("unsafe {{ {call} }}")
    } else {
        call
    };
    let _ = match callable.drain {
        Drain::None => writeln!(body, "    let _ = {call};"),
        Drain::Iterator => writeln!(body, "    for _item in {call} {{}}"),
        Drain::IteratorInResult => writeln!(
            body,
            "    if let Ok(items) = {call} {{\n        for _item in items {{}}\n    }}"
        ),
        Drain::IteratorInOption => writeln!(
            body,
            "    if let Some(items) = {call} {{\n        for _item in items {{}}\n    }}"
        ),
    };
    if matches!(callable.call, CallForm::Method { .. }) {
        *body = body.replace(
            "    let mut value",
            "    #[allow(unused_mut)]\n    let mut value",
        );
    }
}

/// Integers above this, passed as a size, make the fuzzer find nothing but
/// allocation failures.
const SIZE_CAP: u32 = 1024;

const SIZE_WORDS: &[&str] = &[
    "width", "height", "len", "length", "size", "count", "capacity", "cap", "rows", "cols",
    "columns", "n", "num", "depth", "limit", "max", "w", "h",
];

/// An integer parameter named like a size or count (`width`, `max_len`).
fn is_size_like(param: &HarnessParam) -> bool {
    let ArgForm::Value {
        field,
        pass: super::types::Pass::Owned,
    } = &param.form
    else {
        return false;
    };
    let integer = matches!(
        field.as_str(),
        "u8" | "u16" | "u32" | "u64" | "u128" | "usize" | "i16" | "i32" | "i64" | "i128" | "isize"
    );
    integer
        && param
            .name
            .split('_')
            .any(|word| SIZE_WORDS.contains(&word.to_ascii_lowercase().as_str()))
}

fn escape(text: &str) -> String {
    text.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('{', "{{")
        .replace('}', "}}")
}

fn is_prelude_trait(path: &str) -> bool {
    matches!(
        path,
        "std::convert::From"
            | "std::convert::TryFrom"
            | "std::iter::Iterator"
            | "std::default::Default"
    )
}

/// A new `fuzz/Cargo.toml` for `package` at `crate_path` (relative to the
/// fuzz directory), with one `[[bin]]` per target.
pub fn cargo_toml(package: &str, crate_path: &str, targets: &[&str]) -> String {
    let mut out = format!(
        "[package]\nname = \"{package}-fuzz\"\nversion = \"0.0.0\"\npublish = false\n\
         edition = \"2021\"\n\n[package.metadata]\ncargo-fuzz = true\n\n[dependencies]\n\
         libfuzzer-sys = \"0.4\"\narbitrary = {{ version = \"1\", features = [\"derive\"] }}\n\n\
         [dependencies.{package}]\npath = \"{crate_path}\"\n\n\
         # A workspace of its own, so a parent workspace does not claim it.\n\
         [workspace]\nmembers = [\".\"]\n"
    );
    for target in targets {
        out.push_str(&bin_entry(target));
    }
    out
}

fn bin_entry(target: &str) -> String {
    format!(
        "\n[[bin]]\nname = \"{target}\"\npath = \"fuzz_targets/{target}.rs\"\ntest = false\n\
         doc = false\nbench = false\n"
    )
}

/// `existing` with a `[[bin]]` for `target` (and the `arbitrary`
/// dependency when `needs_arbitrary`), or `None` when it has both.
pub fn update_cargo_toml(existing: &str, target: &str, needs_arbitrary: bool) -> Option<String> {
    let has_bin = existing.contains(&format!("name = \"{target}\""));
    let has_arbitrary = existing
        .lines()
        .any(|line| line.trim_start().starts_with("arbitrary"));
    if has_bin && (has_arbitrary || !needs_arbitrary) {
        return None;
    }
    let mut out = String::new();
    let mut added_dep = has_arbitrary || !needs_arbitrary;
    for line in existing.lines() {
        out.push_str(line);
        out.push('\n');
        if !added_dep && line.trim() == "[dependencies]" {
            out.push_str("arbitrary = { version = \"1\", features = [\"derive\"] }\n");
            added_dep = true;
        }
    }
    if !added_dep {
        out.push_str(
            "\n[dependencies]\narbitrary = { version = \"1\", features = [\"derive\"] }\n",
        );
    }
    if !has_bin {
        out.push_str(&bin_entry(target));
    }
    Some(out)
}

/// Where the harness goes: `out`, or `<crate>/fuzz`.
pub fn fuzz_dir(project_root: &Path, callable: &RustCallable, out: Option<&Path>) -> PathBuf {
    match out {
        Some(dir) if dir.is_absolute() => dir.to_path_buf(),
        Some(dir) => project_root.join(dir),
        None => project_root.join(&callable.krate.dir).join("fuzz"),
    }
}

/// Write the harness (and `Cargo.toml`) under `dir`. An existing target
/// file with other content is kept unless `force` — it may hold the
/// author's filled-in TODOs.
pub fn write(
    project_root: &Path,
    callable: &RustCallable,
    harness: &HarnessText,
    dir: &Path,
    force: bool,
) -> Result<Vec<WrittenFile>, String> {
    let crate_dir = project_root.join(&callable.krate.dir);
    let crate_path = if dir == crate_dir.join("fuzz") {
        "..".to_string()
    } else {
        crate_dir
            .canonicalize()
            .unwrap_or_else(|_| crate_dir.clone())
            .to_string_lossy()
            .to_string()
    };
    let targets_dir = dir.join("fuzz_targets");
    std::fs::create_dir_all(&targets_dir)
        .map_err(|e| format!("cannot create {}: {e}", targets_dir.display()))?;
    let mut written = Vec::new();

    let manifest = dir.join("Cargo.toml");
    let (content, status) = match std::fs::read_to_string(&manifest) {
        Ok(existing) => {
            match update_cargo_toml(&existing, &harness.target, harness.needs_arbitrary) {
                Some(updated) => (Some(updated), "updated"),
                None => (None, "unchanged"),
            }
        }
        Err(_) => (
            Some(cargo_toml(
                &callable.krate.package,
                &crate_path,
                &[harness.target.as_str()],
            )),
            "created",
        ),
    };
    if let Some(content) = content {
        std::fs::write(&manifest, content)
            .map_err(|e| format!("cannot write {}: {e}", manifest.display()))?;
    }
    written.push(WrittenFile {
        path: manifest.to_string_lossy().to_string(),
        status,
    });

    let file = targets_dir.join(format!("{}.rs", harness.target));
    let status = match std::fs::read_to_string(&file) {
        Ok(existing) if existing == harness.source => "unchanged",
        Ok(_) if !force => {
            return Err(format!(
                "{} exists with other content (edited?); pass --force to overwrite it",
                file.display()
            ));
        }
        Ok(_) => "updated",
        Err(_) => "created",
    };
    if status != "unchanged" {
        std::fs::write(&file, &harness.source)
            .map_err(|e| format!("cannot write {}: {e}", file.display()))?;
    }
    written.push(WrittenFile {
        path: file.to_string_lossy().to_string(),
        status,
    });

    let gitignore = dir.join(".gitignore");
    if !gitignore.exists() {
        std::fs::write(&gitignore, "target\ncorpus\nartifacts\ncoverage\nlogs\n")
            .map_err(|e| format!("cannot write {}: {e}", gitignore.display()))?;
        written.push(WrittenFile {
            path: gitignore.to_string_lossy().to_string(),
            status: "created",
        });
    }
    Ok(written)
}

/// Parameters as golden tests build them.
#[cfg(test)]
pub(crate) fn param(name: &str, ty: &str) -> HarnessParam {
    HarnessParam {
        name: name.to_string(),
        ty: ty.to_string(),
        form: super::types::classify(ty, &std::collections::HashMap::new()),
    }
}

#[cfg(test)]
mod tests {
    use super::super::Constructor;
    use super::super::api::CrateInfo;
    use super::*;
    use crate::analyze::bugs::FnSpan;

    fn callable(call: CallForm, params: Vec<HarnessParam>) -> RustCallable {
        RustCallable {
            span: FnSpan {
                id: "id".into(),
                name: "decode".into(),
                qualified_name: "decode".into(),
                kind: "function".into(),
                file: "src/lib.rs".into(),
                start_line: 10,
                end_line: 20,
                start_col: 0,
                signature: None,
                return_type: None,
                is_test: false,
            },
            krate: CrateInfo {
                dir: String::new(),
                package: "demo-codec".into(),
                lib_name: "demo_codec".into(),
                src_dir: "src".into(),
                lib_root: "src/lib.rs".into(),
            },
            call,
            owner: None,
            params,
            turbofish: None,
            trait_import: None,
            is_async: false,
            is_unsafe: false,
            drain: Drain::None,
            todos: Vec::new(),
        }
    }

    #[test]
    fn golden_bytes_slice() {
        let harness = render(&callable(
            CallForm::Path("demo_codec::decode".into()),
            vec![param("input", "&[u8]")],
        ));
        assert_eq!(harness.target, "decode");
        assert!(!harness.needs_arbitrary);
        assert_eq!(
            harness.source,
            "#![no_main]
//! Fuzz `demo_codec::decode` (src/lib.rs:10).
//!
//! Generated by `codegraph analyze fuzz-harness`; run it with
//! `cargo +nightly fuzz run decode`.

use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    let _ = demo_codec::decode(data);
});
"
        );
    }

    #[test]
    fn golden_str_skips_invalid_utf8() {
        let harness = render(&callable(
            CallForm::Path("demo_codec::text::parse".into()),
            vec![param("source", "&str")],
        ));
        assert_eq!(harness.target, "text_parse");
        assert_eq!(
            harness.source,
            "#![no_main]
//! Fuzz `demo_codec::text::parse` (src/lib.rs:10).
//!
//! Generated by `codegraph analyze fuzz-harness`; run it with
//! `cargo +nightly fuzz run text_parse`.

use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    let Ok(text) = std::str::from_utf8(data) else {
        return;
    };
    let _ = demo_codec::text::parse(text);
});
"
        );
    }

    #[test]
    fn golden_multi_arg_uses_an_arbitrary_input() {
        let harness = render(&callable(
            CallForm::Path("demo_codec::decode".into()),
            vec![
                param("blurhash", "&str"),
                param("width", "u32"),
                param("punch", "f32"),
                param("pixels", "&mut [u8]"),
            ],
        ));
        assert!(harness.needs_arbitrary);
        assert_eq!(
            harness.source,
            "#![no_main]
//! Fuzz `demo_codec::decode` (src/lib.rs:10).
//!
//! Generated by `codegraph analyze fuzz-harness`; run it with
//! `cargo +nightly fuzz run decode`.

use libfuzzer_sys::fuzz_target;

#[derive(arbitrary::Arbitrary, Debug)]
struct Input {
    blurhash: String,
    width: u32,
    punch: f32,
    pixels: Vec<u8>,
}

fuzz_target!(|input: Input| {
    // Size-like arguments (width) are taken modulo 1024 so allocations stay bounded.
    let mut input = input;
    let _ = demo_codec::decode(input.blurhash.as_str(), input.width % 1024, input.punch, input.pixels.as_mut_slice());
});
"
        );
    }

    #[test]
    fn golden_method_with_new_constructor() {
        let mut target = callable(
            CallForm::Method {
                name: "feed".into(),
                owner_path: "demo_codec::Decoder".into(),
                constructor: Some(Constructor {
                    call: "demo_codec::Decoder::new".into(),
                    label: "Decoder::new".into(),
                    params: vec![],
                    wrap: Wrap::Plain,
                }),
            },
            vec![param("chunk", "&[u8]")],
        );
        target.owner = Some("Decoder".into());
        let harness = render(&target);
        assert_eq!(harness.target, "decoder_feed");
        assert_eq!(
            harness.source,
            "#![no_main]
//! Fuzz `demo_codec::Decoder::feed` (src/lib.rs:10).
//!
//! Generated by `codegraph analyze fuzz-harness`; run it with
//! `cargo +nightly fuzz run decoder_feed`.

use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[u8]| {
    #[allow(unused_mut)]
    let mut value = demo_codec::Decoder::new();
    let _ = value.feed(data);
});
"
        );

        // A fallible constructor with its own input goes through the struct.
        if let CallForm::Method {
            constructor: Some(constructor),
            ..
        } = &mut target.call
        {
            constructor.params = vec![HarnessParam {
                name: "new_limit".into(),
                ..param("limit", "usize")
            }];
            constructor.wrap = Wrap::Result;
        }
        let harness = render(&target);
        assert!(
            harness
                .source
                .contains("    new_limit: usize,\n    chunk: Vec<u8>,\n"),
            "{}",
            harness.source
        );
        assert!(
            harness.source.contains(
                "    let Ok(mut value) = demo_codec::Decoder::new(input.new_limit % 1024) else {\n        return;\n    };\n    let _ = value.feed(input.chunk.as_slice());\n"
            ),
            "{}",
            harness.source
        );
    }

    #[test]
    fn opaque_values_become_todos() {
        let mut target = callable(
            CallForm::Path("demo_codec::decode_with".into()),
            vec![param("data", "&[u8]"), param("config", "Config")],
        );
        target.todos = vec!["build `config: Config`".into()];
        let harness = render(&target);
        assert!(harness.source.contains("// TODO: build `config: Config`\n"));
        assert!(
            harness
                .source
                .contains("    let config = todo!(\"build `config: Config`\");\n")
        );
        assert!(
            harness
                .source
                .contains("demo_codec::decode_with(data, config)")
        );
        assert!(
            harness
                .source
                .starts_with("#![no_main]\n#![allow(unreachable_code, unused_variables)]\n")
        );
    }

    #[test]
    fn lazy_iterators_are_drained() {
        let mut target = callable(
            CallForm::Path("demo_codec::entries".into()),
            vec![param("buf", "&[u8]")],
        );
        target.drain = Drain::IteratorInResult;
        let harness = render(&target);
        assert!(
            harness.source.contains(
                "    if let Ok(items) = demo_codec::entries(data) {\n        for _item in items {}\n    }\n"
            ),
            "{}",
            harness.source
        );
    }

    #[test]
    fn readers_get_a_cursor() {
        let harness = render(&callable(
            CallForm::Path("demo_codec::read".into()),
            vec![param("r", "&mut dyn std::io::Read")],
        ));
        assert!(
            harness
                .source
                .contains("demo_codec::read(&mut std::io::Cursor::new(data))")
        );
    }

    #[test]
    fn cargo_toml_is_created_then_extended() {
        let manifest = cargo_toml("demo-codec", "..", &["decode"]);
        assert!(manifest.contains("[dependencies.demo-codec]\npath = \"..\"\n"));
        assert!(manifest.contains("[[bin]]\nname = \"decode\"\npath = \"fuzz_targets/decode.rs\""));
        assert_eq!(update_cargo_toml(&manifest, "decode", true), None);
        let updated = update_cargo_toml(&manifest, "parse", false).unwrap();
        assert!(updated.contains("name = \"parse\""));
        let bare = "[package]\nname = \"x-fuzz\"\n\n[dependencies]\nlibfuzzer-sys = \"0.4\"\n";
        let updated = update_cargo_toml(bare, "parse", true).unwrap();
        assert!(updated.contains("[dependencies]\narbitrary = { version = \"1\", features = [\"derive\"] }\nlibfuzzer-sys"));
    }
}
